"""
Pydantic schemas for request/response validation.
"""

from backend.schemas.contractor import (
    ContractorBase,
    ContractorCreate,
    ContractorUpdate,
    ContractorResponse,
    ContractorListItem,
    AssignmentBase,
    AssignmentCreate,
    AssignmentUpdate,
    EndAssignmentRequest,
    AssignmentResponse,
    AssignmentWithDetails,
)

from backend.schemas.payment import (
    PaymentCreate,
    PaymentResponse,
    PaymentListItem,
    EarningsResponse,
    EarningsDetailResponse,
    EarningsSummary,
    AllocationResponse,
    AllocationRequest,
)

from backend.schemas.onboarding import (
    InvitationCreate,
    InvitationResponse,
    OnboardingStatusItem,
    VerifyTokenResponse,
    SetupAccountRequest,
    SetupAccountResponse,
    UpdateProfileRequest,
    CompleteProfileResponse,
)

from backend.schemas.contract import (
    ContractResponse,
    ContractListItem,
    SignContractRequest,
    SignatureResponse,
    GenerateAmendmentRequest,
)

from backend.schemas.manager import (
    ManagerBase,
    ManagerCreate,
    ManagerUpdate,
    ManagerResponse,
    ManagerListItem,
    ManagerAssignmentCreate,
    ManagerAssignmentUpdate,
    EndManagerAssignmentRequest,
    ManagerAssignmentResponse,
    ManagerEarningsResponse,
    ManagerEarningsSummary,
    DeviceCreate,
    DeviceUpdate,
    DeviceResponse,
)

from backend.schemas.bank_account import (
    BankAccountBase,
    BankAccountCreate,
    BankAccountUpdate,
    BankAccountResponse,
    UnassignedAccountInfo,
    AccountAssignmentItem,
    AccountAssignmentRequest,
    AccountAssignmentResponse,
    CheckAccountsResponse,
    PaystubAccountSplitBase,
    PaystubAccountSplitCreate,
    PaystubAccountSplitResponse,
    PaystubAccountSplitWithDetails,
)

__all__ = [
    "ContractorBase",
    "ContractorCreate",
    "ContractorUpdate",
    "ContractorResponse",
    "ContractorListItem",
    "AssignmentBase",
    "AssignmentCreate",
    "AssignmentUpdate",
    "EndAssignmentRequest",
    "AssignmentResponse",
    "AssignmentWithDetails",
    "PaymentCreate",
    "PaymentResponse",
    "PaymentListItem",
    "EarningsResponse",
    "EarningsDetailResponse",
    "EarningsSummary",
    "AllocationResponse",
    "AllocationRequest",
    "BankAccountBase",
    "BankAccountCreate",
    "BankAccountUpdate",
    "BankAccountResponse",
    "UnassignedAccountInfo",
    "AccountAssignmentItem",
    "AccountAssignmentRequest",
    "AccountAssignmentResponse",
    "CheckAccountsResponse",
    "PaystubAccountSplitBase",
    "PaystubAccountSplitCreate",
    "PaystubAccountSplitResponse",
    "PaystubAccountSplitWithDetails",
    "InvitationCreate",
    "InvitationResponse",
    "OnboardingStatusItem",
    "VerifyTokenResponse",
    "SetupAccountRequest",
    "SetupAccountResponse",
    "UpdateProfileRequest",
    "CompleteProfileResponse",
    "ContractResponse",
    "ContractListItem",
    "SignContractRequest",
    "SignatureResponse",
    "GenerateAmendmentRequest",
    "ManagerBase",
    "ManagerCreate",
    "ManagerUpdate",
    "ManagerResponse",
    "ManagerListItem",
    "ManagerAssignmentCreate",
    "ManagerAssignmentUpdate",
    "EndManagerAssignmentRequest",
    "ManagerAssignmentResponse",
    "ManagerEarningsResponse",
    "ManagerEarningsSummary",
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceResponse",
]
